# Generated by Django 3.2.9 on 2021-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('website', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('sizeProm', models.FloatField()),
                ('locality', models.CharField(blank=True, max_length=30, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('industry', models.CharField(blank=True, max_length=40, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
