# Generated by Django 3.2.9 on 2021-11-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compania',
            new_name='Company',
        ),
    ]
