# Generated by Django 3.2.9 on 2021-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('founded', models.IntegerField()),
                ('size', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('industry', models.CharField(max_length=40)),
                ('linkedin_url', models.CharField(max_length=100)),
            ],
        ),
    ]
