# Generated by Django 3.2.9 on 2021-11-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companias', '0002_auto_20211124_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compania',
            name='id',
            field=models.CharField(max_length=80, primary_key=True, serialize=False),
        ),
    ]
