# Generated by Django 3.2.9 on 2021-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companias', '0003_alter_compania_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='compania',
            name='sizeProm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
